### ISSUE TITLE
java.lang.NoSuchMethodException: is64Bit

### ISSUE THREAD

**Issue by lxzh** [ljf1239848066/epic#1]
```
10-15 03:59:03.742 8947-8947/me.weishu.epic.samples E/Runtime: get is64Bit failed, default not 64bit!
    java.lang.NoSuchMethodException: is64Bit []
        at java.lang.Class.getConstructorOrMethod(Class.java:472)
        at java.lang.Class.getDeclaredMethod(Class.java:640)
        at com.taobao.android.dexposed.utility.Runtime.<clinit>(Runtime.java:37)
        at de.robv.android.xposed.DexposedBridge.hookMethod(DexposedBridge.java:120)
        at de.robv.android.xposed.DexposedBridge.findAndHookMethod(DexposedBridge.java:176)
        at me.weishu.epic.samples.tests.returntype.VoidType.test(VoidType.java:26)
        at me.weishu.epic.samples.MainActivity$MyAdapter$1.onClick(MainActivity.java:106)
        at android.view.View.performClick(View.java:4438)
        at android.view.View$PerformClick.run(View.java:18422)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
```

## DeviceInfo:
 API:19
 x86
 ARMv7 Processor rev 3 (v7l)

**Comment by lxzh** [comment]
@
